# BiasingManager configuration.

[biasing]
enabled = true

[biasing.xs]
particles = proton
processes = protonInelastic
factor = 1000
only_primary = true
apply_to_secondaries = false
min_weight = 0.05
max_interactions = 5
volumes = Target
