# ScoringManager configuration.

[scoring]
enabled = true
hits = true
event_edep = true
edep = true
let = false
dose = false
fluence = false
auto_create_default_scorers = true
verbose = 1

[scoring.edep]
raw_histogram = true
weighted_histogram = true
bins = 200
min = 0 eV
max = 10 MeV
volume_summary = true
particle_summary = true
