# LayeredDeviceTemplate geometry configuration.

[world]
size = 20 cm, 20 cm, 20 cm
material = G4_AIR

[layers]
count = 3
names = Substrate, Oxide, Metal
auto_stack = true
axis = z
gap = 0 um

[layer.Substrate]
thickness = 500 um
xy = 10 mm, 10 mm
material = G4_Si
sensitive = false
bias = false
region = SubstrateRegion

[layer.Oxide]
thickness = 1 um
xy = 10 mm, 10 mm
material = G4_WATER
sensitive = true
bias = false
region = OxideRegion
cut.e- = 100 nm

[layer.Metal]
thickness = 2 um
xy = 10 mm, 10 mm
material = G4_Cu
sensitive = true
bias = true
region = MetalRegion
