# ShieldingTemplate geometry configuration.

[world]
size = 1 m, 1 m, 1 m
material = G4_AIR

[shielding]
axis = z
area = 10 cm, 10 cm
start = -10 cm
gap = 0 mm
layers = Lead, Polyethylene

[shield.Lead]
thickness = 5 cm
material = G4_Pb
bias = true
region = LeadRegion

[shield.Polyethylene]
thickness = 10 cm
material = G4_POLYETHYLENE
bias = false
region = PolyRegion

[detector]
size = 10 cm, 10 cm, 1 cm
material = G4_Si
position = 0 mm, 0 mm, 20 cm
sensitive = true
region = DetectorRegion
