/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/AIHL/material/load config/materials/material.ini
/AIHL/geometry/setTemplate array
/AIHL/geometry/loadConfig config/geometry/array.ini
/AIHL/geometry/checkOverlaps true
/AIHL/geometry/printTree
/AIHL/physics/setReferenceList FTFP_BERT_EMZ
/AIHL/physics/setDefaultCut 1 mm
/AIHL/source/preset proton_beam
/AIHL/scoring/enable true
/AIHL/scoring/edep true

/run/initialize
/control/execute macros\vis.mac
/run/beamOn 100
